#!/usr/bin/env node
// Generates docs/deploy/env.md (the block between the env-docs markers) and .env.example from the two
// env parsers plus scripts/env-meta.mjs, so the reference cannot drift from the code.
//
//   node scripts/env-docs.mjs            regenerate both files (alias: pnpm env:docs)
//   node scripts/env-docs.mjs --check    exit 1 if a parsed key lacks metadata, metadata is stale, or
//                                        either file differs from what would be generated (CI, pnpm lint)
//   --root <dir>                         read/write a different checkout (tests use a temp copy)
//
// Parsing is deliberately plain regex: env.ts keeps one `KEY: z...` per line inside `z.object({`, and
// config.py keeps one `"KEY": "literal" | None` per line inside `DEFAULTS = {`. Anything else fails loudly.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { SECTIONS } from "./env-meta.mjs";

const ENV_TS = "packages/shared/src/env.ts";
const CONFIG_PY = "workers/media/hub_worker/config.py";
const EXAMPLE = ".env.example";
const DOC = "docs/deploy/env.md";
const BEGIN = "<!-- env-docs:begin (generated by scripts/env-docs.mjs; edit scripts/env-meta.mjs) -->";
const END = "<!-- env-docs:end -->";

const args = process.argv.slice(2);
const check = args.includes("--check");
const rootArg = args.indexOf("--root");
const ROOT = rootArg >= 0 ? resolve(args[rootArg + 1]) : resolve(dirname(fileURLToPath(import.meta.url)), "..");

const errors = [];
const read = (rel) => readFileSync(join(ROOT, rel), "utf8").replace(/\r\n/g, "\n");

/** env.ts: Map KEY -> { kind: "default", value } | { kind: "optional" } | { kind: "required" } */
function parseEnvTs(src) {
  const start = src.indexOf("z.object({");
  const end = src.indexOf("\n});", start);
  if (start < 0 || end < 0) {
    errors.push(`${ENV_TS}: could not find the \`z.object({ ... })\` schema`);
    return new Map();
  }
  const keys = new Map();
  for (const line of src.slice(start, end).split("\n").slice(1)) {
    if (!line.trim() || line.trim().startsWith("//")) continue;
    // a trailing comment needs whitespace before `//`, so "http://..." defaults stay intact
    const m = line.match(/^ {2}([A-Z][A-Z0-9_]*):\s*(z\..*?),?(\s+\/\/.*)?$/);
    if (!m) {
      errors.push(`${ENV_TS}: cannot parse schema line \`${line.trim()}\` (keep one KEY: z... per line)`);
      continue;
    }
    const def = m[2].match(/\.default\(\s*("(?:[^"\\]|\\.)*"|[^)]*?)\s*\)/);
    if (def) keys.set(m[1], { kind: "default", value: def[1].startsWith('"') ? JSON.parse(def[1]) : def[1] });
    else if (m[2].includes(".optional()")) keys.set(m[1], { kind: "optional" });
    else keys.set(m[1], { kind: "required" });
  }
  return keys;
}

/** config.py: Map KEY -> { kind: "default", value } | { kind: "none" } */
function parseConfigPy(src) {
  const start = src.search(/^DEFAULTS\b.*=\s*\{\s*$/m);
  const end = src.indexOf("\n}", start);
  const keys = new Map();
  if (start < 0 || end < 0) {
    errors.push(`${CONFIG_PY}: could not find the \`DEFAULTS = { ... }\` dict`);
    return keys;
  }
  for (const line of src.slice(start, end).split("\n").slice(1)) {
    if (!line.trim() || line.trim().startsWith("#")) continue;
    const m = line.match(/^\s+"([A-Z][A-Z0-9_]*)":\s*(None|"((?:[^"\\]|\\.)*)"),?\s*(#.*)?$/);
    if (!m) {
      errors.push(`${CONFIG_PY}: cannot parse DEFAULTS line \`${line.trim()}\` (use "KEY": "literal" or None)`);
      continue;
    }
    keys.set(m[1], m[2] === "None" ? { kind: "none" } : { kind: "default", value: m[3] });
  }
  for (const m of src.matchAll(/(?:\bgetenv\(|\bget\(|\benviron\[)\s*"([A-Z][A-Z0-9_]*)"/g)) {
    if (!keys.has(m[1])) {
      errors.push(`${m[1]}: read in ${CONFIG_PY} but missing from its DEFAULTS dict, so ${EXAMPLE} and ${DOC} cannot list it`);
      keys.set(m[1], { kind: "none" });
    }
  }
  return keys;
}

const tsKeys = parseEnvTs(read(ENV_TS));
const pyKeys = parseConfigPy(read(CONFIG_PY));

const meta = new Map();
for (const section of SECTIONS) for (const [key, m] of Object.entries(section.vars)) meta.set(key, m);

for (const [file, keys] of [[ENV_TS, tsKeys], [CONFIG_PY, pyKeys]]) {
  for (const key of keys.keys()) {
    if (!meta.has(key)) {
      errors.push(`${key}: read by ${file} but has no entry in scripts/env-meta.mjs, so ${EXAMPLE} has no line for it (add one, then run \`pnpm env:docs\`)`);
    }
  }
}
for (const [key, m] of meta) {
  if (!tsKeys.has(key) && !pyKeys.has(key) && !m.readBy?.length && !m.planned) {
    errors.push(`${key}: listed in scripts/env-meta.mjs but read by neither parser; remove it or set readBy/planned`);
  }
  if (!["required", "optional", "planned"].includes(m.production)) errors.push(`${key}: production must be required|optional|planned`);
}

// ── rendering ──

const cell = (s) => String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");
const code = (s) => `\`${s}\``;

function consumers(key) {
  const m = meta.get(key);
  return [...(tsKeys.has(key) ? ["web", "admin"] : []), ...(pyKeys.has(key) ? ["worker"] : []), ...(m.readBy ?? [])];
}

function defaultText(key) {
  const m = meta.get(key);
  const describe = (d) => {
    if (!d) return null;
    if (d.kind === "default") return m.secret ? "local dev value (masked)" : code(d.value);
    if (d.kind === "required") return "none: must be set";
    return m.derived ? `derived: ${m.derived}` : "unset";
  };
  const ts = describe(tsKeys.get(key));
  const py = describe(pyKeys.get(key));
  if (ts && py && ts !== py) return `web/admin: ${ts}; worker: ${py}`;
  return ts ?? py ?? (m.planned ? `not read yet (${m.planned})` : "unset");
}

function localText(key) {
  const m = meta.get(key);
  if (m.example === undefined) return "commented out (default applies)";
  return m.secret ? "dev placeholder" : code(m.example);
}

const PRODUCTION = { required: "**required**", optional: "optional", planned: "planned" };

function renderDoc() {
  const out = [BEGIN, ""];
  out.push(`${meta.size} variables. Read by: web/admin = \`${ENV_TS}\` (Zod), worker = \`${CONFIG_PY}\` (DEFAULTS).`);
  for (const section of SECTIONS) {
    out.push("", `### ${section.title}`, "");
    out.push("| Variable | Read by | Default | Local (`.env.example`) | Production | Secret | Source / owner | Notes |");
    out.push("|---|---|---|---|---|---|---|---|");
    for (const [key, m] of Object.entries(section.vars)) {
      out.push(
        `| ${code(key)} | ${cell(consumers(key).join(", ") || "nobody yet")} | ${cell(defaultText(key))} | ${cell(localText(key))} | ` +
          `${PRODUCTION[m.production]} | ${m.secret ? "secret" : "no"} | ${cell(m.owner ?? "")} | ${cell(m.notes ?? "")} |`,
      );
    }
  }
  out.push("", END);
  return out.join("\n");
}

function renderExample() {
  const out = [
    "# Generated by scripts/env-docs.mjs from packages/shared/src/env.ts, workers/media/hub_worker/config.py",
    "# and scripts/env-meta.mjs. Do not edit by hand: change those, then run `pnpm env:docs`.",
    "# Reference (defaults, secrets, production rules): docs/deploy/env.md",
    "#",
    "# Copy to .env — every service reads the same file (web, admin, worker, prisma).",
    "# Commented-out lines are unset: the default shown applies.",
  ];
  for (const section of SECTIONS) {
    out.push("", `# ─── ${section.title} `.padEnd(60, "─"));
    for (const line of section.intro ?? []) out.push(`# ${line}`);
    for (const [key, m] of Object.entries(section.vars)) {
      if (m.hint) out.push(`# ${m.hint}`);
      if (m.example !== undefined) {
        out.push(`${key}=${m.example}`);
      } else {
        const d = pyKeys.get(key)?.kind === "default" ? pyKeys.get(key) : tsKeys.get(key);
        out.push(`# ${key}=${d?.kind === "default" ? d.value : ""}`);
      }
    }
  }
  return out.join("\n") + "\n";
}

const exampleKeys = (s) => new Set([...s.matchAll(/^#?\s*([A-Z][A-Z0-9_]*)=/gm)].map((m) => m[1]));

if (errors.length === 0) {
  const example = renderExample();
  const block = renderDoc();
  const docPath = join(ROOT, DOC);
  const doc = existsSync(docPath) ? read(DOC) : "";
  const b = doc.indexOf(BEGIN);
  const e = doc.indexOf(END);
  const markersOk = b >= 0 && e > b;
  if (!markersOk) errors.push(`${DOC}: missing the env-docs begin/end markers`);
  const nextDoc = markersOk ? doc.slice(0, b) + block + doc.slice(e + END.length) : doc;
  const currentExample = existsSync(join(ROOT, EXAMPLE)) ? read(EXAMPLE) : "";

  if (check) {
    if (currentExample !== example) {
      const have = exampleKeys(currentExample);
      const missing = [...exampleKeys(example)].filter((k) => !have.has(k));
      errors.push(`${EXAMPLE} is stale${missing.length ? ` (missing: ${missing.join(", ")})` : ""}; run \`pnpm env:docs\``);
    }
    if (markersOk && nextDoc !== doc) errors.push(`${DOC} is stale; run \`pnpm env:docs\``);
  } else if (errors.length === 0) {
    writeFileSync(join(ROOT, EXAMPLE), example);
    writeFileSync(docPath, nextDoc);
  }
}

if (errors.length) {
  for (const e of errors) console.error(`env-docs: ${e}`);
  process.exit(1);
}
console.log(check ? `env docs up to date (${meta.size} variables)` : `wrote ${EXAMPLE} and ${DOC} (${meta.size} variables)`);
